apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rhtap-go-app-24
  janus-idp.io/tekton: rhtap-go-app-24
  backstage.io/kubernetes-id: rhtap-go-app-24
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rhtap-go-app-24
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
